FROM ruby:3.2.3-slim

RUN apt-get update -qq && \
    apt-get install --no-install-recommends -y build-essential libpq-dev curl git && \
    rm -rf /var/lib/apt/lists/*

# Instalar Node.js
RUN curl -fsSL https://deb.nodesource.com/setup_20.x | bash - && \
    apt-get install --no-install-recommends -y nodejs && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app

# Instalar dependências Ruby
COPY Gemfile Gemfile.lock ./
RUN bundle install

# Instalar dependências Node
COPY package.json package-lock.json* ./
RUN npm install

COPY . .
